### PR TITLE
Option to send the user agent

### PR DESCRIPTION
**Pull request by davidmatas**
I have needed to send the user agent to some url so I've thought it is a good idea add it to options

### CODE REVIEW

**Comment by johnotander** [comment]
This is awesome! However, it looks like you still need to update the option [check](https://github.com/jxnblk/get-css/pull/6/files#diff-168726dbe96b3ce427e7fedce31bb0bcR35) to also use the camel case convention. Once you do that I can merge.

**Comment by jxnblk** [comment]
Would it make sense to just assign all options to the request module and not map header to userAgent?

**Comment by johnotander** [comment]
> Would it make sense to just assign all options to the request module and not map header to userAgent?

If I'm understanding that correctly it would also pass the `verbose`/`ignoreCerts` options which are solely used for `get-css`. Though, I suppose they will just end up being ignored on the `request` end of things, so that wouldn't pose a problem. So, maybe? :smiley: 

My one concern with passing all options directly to request is we can't make the options more intuitive for this particular use case. Personally, I think that

```js
getCss('foo.bar', { userAgent: 'foo' })
```

is an appropriate abstraction and cleaner than

```js
getCss('foo.bar', { headers: { 'User-Agent': 'foo' } })
```

**Comment by jxnblk** [comment]
Yeah, sorry I typed that last one on my phone. I get what you're saying about abstracting it out, but it might be nice to just allow any of the options for the request module, and point people to their documentation.

Maybe the other options aren't very useful for the case of `get-css`, but just wanted to put the idea out there.

**Comment by johnotander** [comment]
No worries, just wanted to make sure I parsed it correctly. I think you bring up a great point about being able to direct users to the request documentation. That, on its own, makes it worthwhile to pass along the options directly to request. Otherwise we're reinventing the options/documentation wheel.

**Comment by davidmatas** [comment]
+1 to direct users to request documentation

**Comment by johnotander** [comment]
Closing and readdressing with issue #14. If you'd like to submit a new PR to address it, please feel free, @davidmatas. Thanks!

**Pull request closed without merging**
