### PR TITLE
Handle gzipped html responses

### LINKED ISSUE #7: Errors out with gzipped responses

### PR DESCRIPTION
**Pull request by johnotander**
Closes #7.

### CODE REVIEW

**Comment by johnotander** [comment]
When you get a change, could you please publish this to npm, @jxnblk? Thanks!

**Comment by jxnblk** [comment]
:+1: 

Published. To give you npm publish permissions, do i just need to run `npm owner add <username> get-css`? If so, what's your username?

**Comment by jxnblk** [comment]
Hopefully, you're johno. You should be added now.

**Comment by johnotander** [comment]
Yep, that's me. Awesome, thanks!

**Pull request merged**
